repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-json
    -   id: pretty-format-json
        args: [--autofix, --no-ensure-ascii]
    -   id: check-yaml
    -   id: check-toml
    -   id: check-merge-conflict
    -   id: check-added-large-files
    -   id: no-commit-to-branch
        args: [--branch, master, --branch, main, --branch, release, --pattern, release/.*]
  - repo: https://github.com/psf/black
    rev: 21.7b0
    hooks:
    - id: black
      language_version: python3
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-docstrings
          - flake8-bugbear
          - flake8-builtins
          - pep8-naming
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: "v0.910"
  #   hooks:
  #     - id: mypy
